services:
  currency-exchange:
    image: sumanthgma4/microservices-currency-exchange-service:0.0.1-SNAPSHOT
    # mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    # Enable communication with Eureka Naming Server - override application.properties settings
    # Enable Zipkin tracing - override application.properties settings
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411/

  currency-conversion:
    image: sumanthgma4/microservices-currency-conversion-service:0.0.1-SNAPSHOT
    # mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    # Feign call to currency-exchange service works but rest template call fails - 
    # use the Eureka registered name of the service currency-exchange-service instead of localhost:8000
    # in the URL for rest template call in CurrencyConversionController
    depends_on:
      - naming-server
      - currency-exchange
    # Enable communication with Eureka Naming Server - override application.properties settings
    # Enable Zipkin tracing - override application.properties settings
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411/

  naming-server:
    image: sumanthgma4/microservices-naming-server:0.0.1-SNAPSHOT
    # mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

  api-gateway:
    image: sumanthgma4/microservices-api-gateway:0.0.1-SNAPSHOT
    # mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
    # Enable communication with Eureka Naming Server - override application.properties settings
    # Enable Zipkin tracing - override application.properties settings
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411/

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_security_mysqldb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    networks:
      - currency-network
    volumes:
      - mysql_data:/var/lib/mysql

  auth-server:
    image: sumanthgma4/microservices-auth-server:0.0.1-SNAPSHOT
    # mem_limit: 700m
    ports:
      - "9090:9090"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - mysql
    # Enable communication with Eureka Naming Server - override application.properties settings
    # Enable Zipkin tracing - override application.properties settings
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka/
      # SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/spring_security_mysqldb
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect


  zipkin-server:
    image: openzipkin/zipkin
    # mem_limit: 700m
    ports:
      - "9411:9411"
    networks:
      - currency-network



# Configure a common network for all services
networks:
  currency-network:

# A volume to persist MySQL DB
volumes:
  mysql_data: