spring:
    application:
        name: auth-server

    datasource:
        url: jdbc:mysql://localhost:3306/spring_security
        username: root
        password: sum93917
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update   # create | update | validate | none
        show-sql: true
        properties:
            hibernate:
                format_sql: true

server:
    port: 9090

jwt:
    secret: super-secret-key-super-secret-key-super-secret-key
    expiration: 1800000 # 30 minutes in milliseconds


eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/